# Generated by Django 5.2.8 on 2025-12-21 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('market', models.CharField(blank=True, default='', max_length=20)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='RUNNING', max_length=10)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('prices_count', models.PositiveIntegerField(default=0)),
                ('features_count', models.PositiveIntegerField(default=0)),
                ('duration_sec', models.FloatField(default=0.0)),
                ('warnings', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk', models.CharField(default='MID', max_length=8)),
                ('horizon', models.CharField(default='MID', max_length=8)),
                ('effort', models.CharField(default='OPTIMIZE', max_length=12)),
                ('payload', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reco_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'as_of'], name='idx_reco_user_asof')],
            },
        ),
        migrations.CreateModel(
            name='FeatureDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('r1', models.FloatField(blank=True, null=True)),
                ('r5', models.FloatField(blank=True, null=True)),
                ('r20', models.FloatField(blank=True, null=True)),
                ('r60', models.FloatField(blank=True, null=True)),
                ('vol10', models.FloatField(blank=True, null=True)),
                ('vol20', models.FloatField(blank=True, null=True)),
                ('vol60', models.FloatField(blank=True, null=True)),
                ('mdd10', models.FloatField(blank=True, null=True)),
                ('mdd20', models.FloatField(blank=True, null=True)),
                ('mdd60', models.FloatField(blank=True, null=True)),
                ('news3', models.FloatField(default=0.0)),
                ('news7', models.FloatField(default=0.0)),
                ('news30', models.FloatField(default=0.0)),
                ('vz5', models.FloatField(blank=True, null=True)),
                ('vz20', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', 'date'], name='idx_feature_stock_date')],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='uniq_feature_stock_date')],
            },
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
                ('volume', models.BigIntegerField()),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('listed_shares', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', 'date'], name='idx_stock_date')],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='uniq_stock_date')],
            },
        ),
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('link', models.URLField(max_length=1000, unique=True)),
                ('originallink', models.URLField(blank=True, default='', max_length=1000)),
                ('source', models.CharField(default='NAVER', max_length=30)),
                ('query_used', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_news', to='stocks.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['stock', 'published_at'], name='idx_stocknews_stock_pub')],
            },
        ),
    ]
