# Generated by Django 5.2.8 on 2025-12-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_marketindex_marketindexdaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRateDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('close', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['pair', '-date'], name='stocks_fxra_pair_82ac8c_idx')],
                'unique_together': {('pair', 'date')},
            },
        ),
    ]
