# Generated by Django 5.2.8 on 2025-12-24 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNewsBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.IntegerField(help_text='뉴스 ID (naversearch.News의 PK)')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(max_length=1000)),
                ('pub_date', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_news_bookmark',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'news_id')},
            },
        ),
        migrations.CreateModel(
            name='UserWatchLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text='유튜브 영상 ID', max_length=100)),
                ('video_title', models.CharField(help_text='영상 제목', max_length=200)),
                ('video_description', models.TextField(blank=True, help_text='영상 설명')),
                ('video_thumbnail', models.URLField(blank=True, help_text='영상 썸네일 URL', max_length=500)),
                ('channel_title', models.CharField(blank=True, help_text='채널명', max_length=200)),
                ('published_at', models.CharField(blank=True, help_text='게시일', max_length=100)),
                ('is_watched', models.BooleanField(default=False, help_text='시청 완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_later_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_watch_later',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'video_id')},
            },
        ),
        migrations.CreateModel(
            name='UserYouTubeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='유튜브 채널 ID', max_length=100)),
                ('channel_title', models.CharField(help_text='채널명', max_length=200)),
                ('channel_description', models.TextField(blank=True, help_text='채널 설명')),
                ('channel_thumbnail', models.URLField(blank=True, help_text='채널 썸네일 URL', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_youtube_subscription',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'channel_id')},
            },
        ),
    ]
