# Generated by Django 5.2.8 on 2025-12-24 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usernewsbookmark_userwatchlater_and_more'),
        ('stocks', '0003_fxratedaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0, help_text='매칭 점수 (0~100)')),
                ('recommended_reason', models.TextField(blank=True, help_text='추천 이유')),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_recommendation',
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
