# Generated by Django 5.2.8 on 2025-12-25 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_stockrecommendation'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='매칭 점수 (0~100)')),
                ('recommended_reason', models.TextField(help_text='추천 이유')),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.savingproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saving_recommendation',
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
